baseurl = "http://leighascott.us/"
languageCode = "en-us"
title = "Leigha + Scott"
theme = "hugo-theme-bleak"

[params]
  logo = "/images/superman_logo.png"
  cover = "/images/branches.jpg"
  gplus = "+ScottScoble"
